#!/usr/bin/env bash

set -e

COM_CONFIG="config/install-common-tools.yaml"

if [[ "$OSTYPE" == darwin* ]]; then
    SYS_CONFIG="config/install-osx.conf.yaml"
elif [[ "$OSTYPE" == linux* ]]; then
    SYS_CONFIG="config/install-linux.conf.yaml"
else
    echo "[ERROR] unkown OSTYPE: $OSTYPE"
    exit 1
fi


DOTBOT_DIR="tools/dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${COM_CONFIG}" "${@}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${SYS_CONFIG}" "${@}"
