# Start configuration added by Zim install {{{
#
# Debug: zsh -o SOURCE_TRACE
#
: ${ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim}

setopt null_glob
setopt extended_glob

if [[ "$OSTYPE" == darwin* ]]; then
    BASEDIR=$(dirname $(/usr/local/opt/coreutils/libexec/gnubin/readlink -f ${(%):-%N}))
else
    BASEDIR=$(dirname $(readlink -f ${(%):-%N}))
fi

# Include all pathes in subdirectory
for x in ${BASEDIR}/pathes/*; do
    source ${x}
done

# }}} End configuration added by Zim install
