# Debug: zsh -o SOURCE_TRACE
#
setopt null_glob
setopt extended_glob

if [[ "$OSTYPE" == darwin* ]]; then
    BASEDIR=$(dirname $(/usr/local/opt/coreutils/libexec/gnubin/readlink -f ${(%):-%N}))
else
    BASEDIR=$(dirname $(readlink -f ${(%):-%N}))
fi

# Include all variables in subdirectory
for x in ${BASEDIR}/env/*; do
    source ${x}
done
