- defaults:
    link:
        relink: true
    shell:
        stdout: true
        stderr: true

- clean: ['$HOME']

# Homebrew
- shell:
    - [ test -e /usr/local/bin/brew || $HOME/.dotfiles/config/install-homebrew.sh , Installing homebrew ]
      #    - [ brew tap homebrew/bundle , Installing homebrew-bundle ]
      #- [ brew bundle --file=$HOME/.dotfiles/package_manager/Brewfile, Installing homebrew formulae ]

# karabiner
- shell:
    - [. karabiner.sh, setup karabiner's config]
