- defaults:
    link:
        relink: true
    shell:
        stdout: true
        stderr: true

- clean: ['$HOME']

- shell:
    - [git submodule update --init --recursive, Installing submodules]

# Homebrew
- shell:
    - [ test -e /usr/local/bin/brew || $HOME/.dotfiles/config/install-homebrew.sh , Installing homebrew ]
    - [ brew tap homebrew/bundle , Installing homebrew-bundle ]
    - [ brew bundle --file=$HOME/.dotfiles/package_manager/Brewfile, Installing homebrew formulae ]

# Oh-my-zsh
- shell:
    - [ test -d $HOME/.oh-my-zsh || $HOME/.dotfiles/config/install-oh-my-zsh.sh , Installing Oh-My-Zsh ]
    - [ chsh -s /bin/zsh , Change default shell to zsh ]
    - [ rm $HOME/.zshrc , Remove default zshrc ]
    - [ mkdir -p $HOME/.oh-my-zsh/custom/themes , Make the dir of oh-my-zsh themes ]
- link:
    $HOME/.zfunctions: zsh/zfunctions
    $HOME/.oh-my-zsh/custom/themes/pure.zsh-theme: zsh/pure_theme/pure.zsh

# Linking
- link:
    $HOME/bin: bin
    $HOME/ump.sh: bin/upm/upm.sh
    $HOME/.zshrc: zsh/zshrc
    $HOME/.gdbinit: gdb-dashboard/.gdbinit
    $HOME/.gitconfig: gitconfig
    $HOME/.gitignore_global: gitignore_global
    $HOME/.octaverc: octaverc
    $HOME/.tmux.conf: tmux.conf
    $HOME/.vimrc: vim/vimrc

# Vim
- shell:
    - [ test -d $HOME/.vim/bundle/Vundle.vim || $HOME/.dotfiles/config/install-vim.sh , Installing Vundle ]
    - [ vim +PluginInstall +qall , Installing Vim Plugins ]

# karabiner
- shell:
    - [. karabiner.sh, setup karabiner's config]
