- defaults:
    link:
        relink: true
    shell:
        stdout: true
        stderr: true

- clean: ['$HOME']

- shell:
    - [git submodule update --init --recursive, Installing submodules]

# Oh-my-zsh
- shell:
    - [ test -d $HOME/.oh-my-zsh || $HOME/.dotfiles/config/install-oh-my-zsh.sh , Installing Oh-My-Zsh ]
    - [ rm $HOME/.zshrc , Remove default zshrc ]
    - [ mkdir -p $HOME/.oh-my-zsh/custom/themes , Make the dir of oh-my-zsh themes ]
- link:
    $HOME/.oh-my-zsh/custom/themes/powerlevel9k.zsh-theme: zsh/themes/powerlevel9k/powerlevel9k.zsh-theme

# Linking
- link:
    $HOME/bin: bin
    $HOME/upm.sh: bin/upm/upm.sh
    $HOME/.zshrc: zsh/zshrc
    $HOME/.gdbinit: tools/gdb-dashboard/.gdbinit
    $HOME/.gitconfig: gitconfig
    $HOME/.gitignore_global: gitignore_global
    $HOME/.octaverc: octaverc
    $HOME/.tmux.conf: tmux.conf
    $HOME/.vimrc: vim/vimrc
    $HOME/.fzf: tools/fzf
- shell:
    - [ touch $HOME/.dotfiles/zsh/local.aliases, Create empty Local Aliases ]
    - [ $HOME/.fzf/install , Installing Fuzzy Finder ]

# Vim
- shell:
    - [ test -d $HOME/.vim/bundle/Vundle.vim || $HOME/.dotfiles/config/install-vim.sh , Installing Vundle ]
    - [ vim +PluginInstall +qall , Installing Vim Plugins ]

# Post Installation
- shell:
    -
      command: chsh -s /bin/zsh
      stdin: true
      stdout: true
    - [ echo , You need to build YCM. ]
