# ======= ZSH Setting ====== #
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.dotfiles/zsh/custom
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=vim

# ZSH Plugins
plugins=(autojump brew common-aliases git git-flow gitfast osx vi-mode zsh-completions zsh-syntax-highlighting zsh-autosuggestions)

# ZSH Theme
GIT_PS1_SHOWSTASHSTATE=1
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh context dir dir_writable vcs vi_mode)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs command_execution_time)
ZSH_THEME="powerlevel9k"

source $ZSH/oh-my-zsh.sh

#======================== Command History Setting ========================
zshaddhistory () {
  # Don't store the command under these constraints: (1) Len <= 5 (2) cd/ls/git
  COMMAND_STR=${1%%$'\n'}
  [[  ( ${#COMMAND_STR} -le 5) || ( -z $COMMAND_STR ) || ( $COMMAND_STR =~ hist(ory)? ) || \
      ( $COMMAND_STR =~ '^l(s\|l\|a)? \*$' ) || \
      ( $COMMAND_STR =~ '^(d\|gd\|git\ diff\|glp\|gg)$' ) \
  ]] && return 1
  # Don't store the failed command
  whence ${${(z)1}[1]} >| /dev/null && return 1
}

# Remove duplicate items in fzf
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP

# Enable vi-mode
bindkey 'jk' vi-cmd-mode

# Enable completion category
autoload -Uz compinit && compinit

zstyle ':completion:*:' menu yes select
# format all messages not formatted in bold prefixed with ----
zstyle ':completion:*' format '%B---- %d%b'
# format descriptions (notice the vt100 escapes)
zstyle ':completion:*:descriptions'    format $'%{\e[0;31m%}completing %B%d%b%{\e[0m%}'
# bold and underline normal messages
zstyle ':completion:*:messages' format '%B%U---- %d%u%b'
# format in bold red error messages
zstyle ':completion:*:warnings' format "%B$fg[red]%}---- no match for: $fg[white]%d%b"
# let's use the tag name as group name
zstyle ':completion:*' group-name ''
