# ======= ZSH Setting ====== #
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.dotfiles/zsh/custom
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=vim

# ZSH Plugins
# Do not use vi-mode plugins to ruin the arrow key completion
plugins=(
    autojump
    docker
    gitfast
    git-extras
    gitignore
    notify
    vscode
    zsh-256color
    zsh-autosuggestions
    zsh-completions
    zsh-syntax-highlighting
)

# ZSH Theme
GIT_PS1_SHOWSTASHSTATE=1
ZSH_THEME="powerlevel9k"
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh context os_icon dir dir_writable vcs vi_mode)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs command_execution_time)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

source $ZSH/oh-my-zsh.sh

#======================== Command History Setting ========================
function zshaddhistory() { # {{{
  # http://mollifier.hatenablog.com/entry/20090728/p1
  local line cmd
  line=${1%%$'\n'}
  cmd=${line%% *}

  # Add command to history if it meets the following conditions
  [[ ${#line} -ge 5
  && ${cmd} != (l|l[sal])
  && ${cmd} != (c|cd)
  && ${cmd} != (m|man)
  && ${cmd} != (r[mr])
  ]]
} # }}}

# Remove duplicate items in fzf
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP

# Enable completion category
autoload -Uz compinit && compinit

zstyle ':completion:*:' menu yes select
# format all messages not formatted in bold prefixed with ----
zstyle ':completion:*' format '%B---- %d%b'
# format descriptions (notice the vt100 escapes)
zstyle ':completion:*:descriptions'    format $'%{\e[0;31m%}completing %B%d%b%{\e[0m%}'
# bold and underline normal messages
zstyle ':completion:*:messages' format '%B%U---- %d%u%b'
# format in bold red error messages
zstyle ':completion:*:warnings' format "%B$fg[red]%}---- no match for: $fg[white]%d%b"
# let's use the tag name as group name
zstyle ':completion:*' group-name ''

zstyle ':notify:*' notifier terminal-notifier
